# Assignment 7

## Submit as an HTML file

### Print your name below

In [111]:
# Annie Lu

### Import the "pandas" "numpy" and "statsmodels.formula.api" libraries

In [2]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf

#### In the code chunk below read the CSV file named `results.csv` in the `data` <br> folder and print the first 5 rows of the dataset. Browse the dataset.

In [3]:
df = pd. read_csv('data/results.csv')
display(df.head())

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1

### (a)  Check Column Types and Data Cleaning

- Use the function .dtypes to get the column types
- Identify which columns have data types that might need conversion
- The 'milliseconds' column contains string values that should be numeric. Create a new column called 'race_time_ms' that:
    - Converts the column to a numeric data type
    - Replaces any non-numeric values with NaN

In [114]:
# Write your answer here
print(df.dtypes)

df['race_time_ms'] = pd.to_numeric(df['milliseconds'], errors='coerce')
display(df[['milliseconds', 'race_time_ms']])

resultId             int64
raceId               int64
driverId             int64
constructorId        int64
number              object
grid                 int64
position            object
positionText        object
positionOrder        int64
points             float64
laps                 int64
time                object
milliseconds        object
fastestLap          object
rank                object
fastestLapTime      object
fastestLapSpeed     object
statusId             int64
dtype: object

      milliseconds  race_time_ms
0          5690616     5690616.0
1          5696094     5696094.0
2          5698779     5698779.0
3          5707797     5707797.0
4          5708630     5708630.0
...            ...           ...
25835           \N           NaN
25836           \N           NaN
25837           \N           NaN
25838           \N           NaN
25839           \N           NaN

[25840 rows x 2 columns]

### (b) Create Categorical Variables

- Create a new column called 'finish_category' that categorizes the race finish positions as follows:
    - Positions 1-3: 'Podium'
    - Positions 4-10: 'Points'
    - Positions 11-20: 'Midfield'
    - Positions >20: 'Backmarker'

Hint: Use the pd.cut() function

In [5]:
df["finish_category"]=pd.cut(df["positionOrder"], bins=[0, 3,10,20,float('inf')], 
    labels=['Podium', 'Points', 'Midfield', 'Backmarker'],right=True)
df

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,finish_category
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1,Podium
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1,Podium
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1,Podium
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1,Points
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1,Points
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25835,25841,1096,854,210,47,12,16,16,16,0.0,57,\N,\N,39,12,1:29.833,211.632,11,Midfield
25836,25842,1096,825,210,20,16,17,17,17,0.0,57,\N,\N,40,20,1:31.158,208.556,11,Midfield
25837,25843,1096,1,131,44,5,18,18,18,0.0,55,\N,\N,42,11,1:29.788,211.738,9,Midfield
25838,25844,1096,849,3,6,20,19,19,19,0.0,55,\N,\N,45,14,1:30.309,210.517,130,Midfield
25839,25845,1096,4,214,14,10,\N,R,20,0.0,27,\N,\N,24,17,1:30.579,209.889,47,Midfield

### (c) Calculate Race Duration
- For rows where 'milliseconds' is available, create a new column <br>
'race_duration_minutes' that converts milliseconds to minutes by dividing <br>
by (1000*60).
- Display the average race duration by 'constructorId' for the top 5 <br>
constructors with the shortest average race times

In [116]:
df['race_duration_minutes'] = df['race_time_ms'] / (1000*60)
top_constructors = df.groupby('constructorId')['race_duration_minutes'].mean().nsmallest(5)

print(top_constructors)

constructorId
35    76.710777
29    77.604125
41    87.046767
16    89.428828
53    89.658852
Name: race_duration_minutes, dtype: float64

### (d) Driver Performance Analysis

- Calculate the following statistics for each driver, grouped by 'driverId':
    - Average finishing position
    - Total points
    - Number of races completed
    - Best finishing position

- Sort the results by total points in descending order
- Display the top 10 drivers based on total points

In [117]:
driver_stats = df.groupby('driverId').agg(
    avg_finishing_position = ('position', 'mean'),
    total_points = ('points', 'sum'),
    races_completed = ('raceId', 'count'),
    best_finishing_position = ('position', 'min')
).sort_values('total_points', ascending=False)

print(driver_stats.head(10))

          avg_finishing_position  ...  best_finishing_position
driverId                          ...
1                       3.383803  ...                      1.0
20                      5.282443  ...                      1.0
4                       6.257732  ...                      1.0
830                     4.022388  ...                      1.0
8                       6.238596  ...                      1.0
822                     6.296089  ...                      1.0
3                       6.355932  ...                      1.0
30                      3.701245  ...                      1.0
817                     8.261538  ...                      1.0
18                      7.409091  ...                      1.0

[10 rows x 4 columns]

### (e) Linear Regression
Create a linear regression model that predicts 'points' based on 'grid' (starting position) and 'laps' completed <br>
Use the following steps:

- Clean the data to remove any non-numeric values and missing values
- Create the regression formula using smf.ols 
- Display the summary of the regression model using model.summary()

What is the predicted points for a driver starting in position 3 and completing 55 laps?

Hint: Use ```.dropna()''' to remove missing values from the points, grid, and laps <br>
variables.

In [118]:
clean_df = df[['points', 'grid', 'laps']].dropna().apply(pd.to_numeric)
model = smf.ols('points ~ grid + laps', data=clean_df).fit()
print(model.summary())

prediction = model.predict(pd.DataFrame({'grid': [3], 'laps': [55]}))
print(round(prediction.iloc[0], 2))

                            OLS Regression Results
==============================================================================
Dep. Variable:                 points   R-squared:                       0.215
Model:                            OLS   Adj. R-squared:                  0.215
Method:                 Least Squares   F-statistic:                     3530.
Date:                Tue, 25 Mar 2025   Prob (F-statistic):               0.00
Time:                        00:15:28   Log-Likelihood:                -70440.
No. Observations:               25840   AIC:                         1.409e+05
Df Residuals:                   25837   BIC:                         1.409e+05
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.5841      0.054     48.267      0.000       2.479       2.689
grid          -0.2248      0.003    -70.621      0.000      -0.231      -0.219
laps           0.0393      0.001     50.779      0.000       0.038       0.041
==============================================================================
Omnibus:                    15818.159   Durbin-Watson:                   0.715
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           183648.109
Skew:                           2.804   Prob(JB):                         0.00
Kurtosis:                      14.795   Cond. No.                         130.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
4.07